# Generated by Django 5.0.2 on 2024-02-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('Content1', models.TextField()),
                ('img1', models.ImageField(default='', upload_to='about/img1')),
                ('Content2', models.TextField()),
                ('head0', models.TextField()),
                ('para0', models.TextField()),
                ('img2', models.ImageField(default='', upload_to='about/img2')),
            ],
        ),
    ]
