# Generated by Django 4.2.6 on 2024-01-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(blank=True)),
                ('course_image', models.ImageField(default='', upload_to='courses/images')),
                ('Content', models.TextField()),
                ('file', models.FileField(default='None', max_length=250, null='True', upload_to='course_download/')),
            ],
        ),
    ]
