# Generated by Django 4.2.6 on 2024-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webtemplate',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(blank=True)),
                ('web_image', models.ImageField(default='', upload_to='c/images')),
                ('Content', models.CharField(max_length=50)),
                ('sourcecode', models.FileField(default='None', max_length=250, null='True', upload_to='doc/course_download/')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(default='None', max_length=250, null='True', upload_to='doc/course_download/'),
        ),
    ]
