# Generated by Django 4.2.6 on 2024-01-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('img1', models.ImageField(default='', upload_to='about/img1')),
                ('img2', models.ImageField(default='', upload_to='about/img2')),
                ('Content1', models.TextField()),
            ],
        ),
    ]
