# Generated by Django 4.2.6 on 2024-01-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Content2',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='head0',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='para0',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
