# Generated by Django 5.0.2 on 2024-02-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(blank=True)),
                ('course_image', models.ImageField(default='', upload_to='courses/images')),
                ('Content', models.TextField()),
                ('file', models.FileField(default='None', max_length=250, null='True', upload_to='doc/course_download/')),
            ],
        ),
        migrations.CreateModel(
            name='Webtemplate',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(blank=True)),
                ('web_image', models.ImageField(default='', upload_to='c/images')),
                ('Content', models.CharField(max_length=50)),
                ('sourcecode', models.FileField(default='None', max_length=250, null='True', upload_to='doc/course_download/')),
            ],
        ),
    ]
